2019-11-07 15:40:07,392 ERROR: Exception on /login [GET] [in c:\program files\python36\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files\python36\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\program files\python36\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\program files\python36\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\program files\python36\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Clikr\microblog2\app\routes.py", line 75, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\program files\python36\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\program files\python36\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\program files\python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\program files\python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files\python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Clikr\microblog2\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Clikr\microblog2\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\program files\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\program files\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\program files\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\program files\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Clikr\microblog2\app\templates\base.html", line 54, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Clikr\microblog2\app\templates\login.html", line 5, in block "app_content"
    <div class="container" style="background-image: '{{ url_for('static',filename=background.jpg) }}';" >
  File "c:\program files\python36\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'background' is undefined
2019-11-07 15:40:53,876 INFO: Microblog startup [in C:\Clikr\microblog2\app\__init__.py:47]
2019-11-07 15:41:12,110 ERROR: Exception on /login [GET] [in c:\program files\python36\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\program files\python36\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\program files\python36\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files\python36\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\program files\python36\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\program files\python36\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Clikr\microblog2\app\routes.py", line 75, in login
    return render_template('login.html', title='Sign In', form=form)
  File "c:\program files\python36\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "c:\program files\python36\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\program files\python36\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\program files\python36\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\program files\python36\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\program files\python36\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Clikr\microblog2\app\templates\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Clikr\microblog2\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\program files\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\program files\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\program files\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\program files\python36\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "C:\Clikr\microblog2\app\templates\base.html", line 54, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Clikr\microblog2\app\templates\login.html", line 5, in block "app_content"
    <div class="container" style="background-image: '{{ url_for('static',filename=background.jpg) }}';" >
  File "c:\program files\python36\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'background' is undefined
2019-11-07 15:41:56,078 INFO: Microblog startup [in C:\Clikr\microblog2\app\__init__.py:47]
2019-11-07 15:42:18,328 INFO: Microblog startup [in C:\Clikr\microblog2\app\__init__.py:47]
2019-11-07 15:54:19,264 INFO: Microblog startup [in C:\Clikr\microblog2\app\__init__.py:47]
